=== process-project/RSD-process/backend/schemas/mention.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "additionalProperties": false,
    "properties": {
        "author": {
            "type": "string"
        },
        "createdAt": {
            "format": "date-time",
            "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$",
            "type": "string"
        },
        "createdBy": {
            "type": "string"
        },
        "date": {
            "format": "date-time",
            "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$",
            "type": "string"
        },
        "image": {
            "format": "uri",
            "type": "string"
        },
        "isCorporateBlog": {
            "default": false,
            "type": "boolean"
        },
        "primaryKey": {
            "$ref": "definitions.json/key/mention"
        },
        "title": {
            "type": "string"
        },
        "type": {
            "enum": [
                "attachment",
                "blogPost",
                "book",
                "bookSection",
                "computerProgram",
                "conferencePaper",
                "document",
                "interview",
                "journalArticle",
                "magazineArticle",
                "manuscript",
                "newspaperArticle",
                "note",
                "presentation",
                "radioBroadcast",
                "report",
                "thesis",
                "videoRecording",
                "webpage"
            ],
            "type": "string"
        },
        "updatedAt": {
            "format": "date-time",
            "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$",
            "type": "string"
        },
        "updatedBy": {
            "type": "string"
        },
        "url": {
            "format": "uri",
            "type": "string"
        },
        "version": {
            "type": "number"
        },
        "zoteroKey": {
            "type": "string"
        }
    },
    "required": [
        "createdAt",
        "isCorporateBlog",
        "primaryKey",
        "title",
        "type",
        "updatedAt"
    ],
    "title": "Mention schema"
}

=== process-project/RSD-process/mocks/blogs.json
[
  {
    "primaryKey": {
      "collection": "mention",
      "id": "4SVMY3V9"
    },
    "version": 2407,
    "title": "Reading news, visually",
    "type": "blogPost",
    "zoteroKey": "4SVMY3V9",
    "isCorporateBlog": true,
    "date": "2017-08-07T00:00:00Z",
    "url": "https://blog.esciencecenter.nl/reading-news-visually-6e02ea9468e",
    "author": "Maarten van Meersbergen",
    "image": "https://cdn-images-1.medium.com/max/2000/1*36VvqJkQdxzrbozNMfi0og.png",
    "createdAt": "2018-04-20T11:38:00Z",
    "updatedAt": "2018-04-20T11:38:00Z",
    "createdBy": "Scraper",
    "updatedBy": "Scraper"
  }
]
