=== process-project/RSD-process/backend/schemas_example/organization.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "additionalProperties": false,
    "title": "Organization schema",
    "properties": {
        "createdAt": {
            "type": "string"
        },
        "createdBy": {
            "type": ["string", "null"]
        },
        "name": {
            "type": "string"
        },
        "primaryKey": {
            "$ref": "definitions.json/key/organization"
        },
        "updatedAt": {
            "type": "string"
        },
        "updatedBy": {
            "type": ["string", "null"]
        },
        "url": {
            "format": "uri",
            "type": "string"
        }
    },
    "required": [
        "createdAt",
        "name",
        "primaryKey",
        "updatedAt",
        "url"
    ],
    "definitions": {
        "key": {
            "commit": {
                "type": "object",
                "required": [
                    "collection",
                    "id"
                ],
                "additionalProperties": false,
                "properties": {
                    "collection": {
                        "enum": [
                            "commit"
                        ],
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    }
                }
            },
            "mention": {
                "type": "object",
                "required": [
                    "collection",
                    "id"
                ],
                "additionalProperties": false,
                "properties": {
                    "collection": {
                        "enum": [
                            "mention"
                        ],
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    }
                }
            },
            "person": {
                "type": "object",
                "required": [
                    "collection",
                    "id"
                ],
                "additionalProperties": false,
                "properties": {
                    "collection": {
                        "enum": [
                            "person"
                        ],
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    }
                }
            },
            "project": {
                "type": "object",
                "required": [
                    "collection",
                    "id"
                ],
                "additionalProperties": false,
                "properties": {
                    "collection": {
                        "enum": [
                            "project"
                        ],
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    }
                }
            },
            "organization": {
                "type": "object",
                "required": [
                    "collection",
                    "id"
                ],
                "additionalProperties": false,
                "properties": {
                    "collection": {
                        "enum": [
                            "organization"
                        ],
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    }
                }
            },
            "software": {
                "type": "object",
                "required": [
                    "collection",
                    "id"
                ],
                "additionalProperties": false,
                "properties": {
                    "collection": {
                        "enum": [
                            "software"
                        ],
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    }
                }
            }
        }
    }
}

=== process-project/RSD-process/mocks/organizations.json
[
  {
    "primaryKey": {
      "id": "nlesc",
      "collection": "organization"
    },
    "createdAt": "2017-11-10T14:12:55Z",
    "updatedAt": "2017-11-10T14:17:53Z",
    "name": "Netherlands eScience Center",
    "url": "http://www.esciencecenter.nl/"
  },
  {
    "primaryKey": {
      "id": "nikhef",
      "collection": "organization"
    },
    "createdAt": "2017-11-10T14:12:55Z",
    "updatedAt": "2017-11-10T14:17:53Z",
    "name": "NIKHEF",
    "url": "http://www.nikhef.nl/"
  }
]
